### PR TITLE
init release-0.6

### PR DESCRIPTION
**Pull request by bojand**
Hello, 
Just wanted to get the discussion started for cutting a new release to include changes since 0.5: #49, #50, and #51. I am not sure what the process is exactly... There was PR #47 for 0.5, but that went to `release-0.5` branch... So I imagine this should go into `release-0.6` branch that someone should create? Anyway just looking for guidance and to get the process going for a release if it's agreeable with everyone to publish a new release. Thanks.

### CODE REVIEW

**Comment by benjaminhuo** [comment]
@wanjunlei Would you create a doc to elaborate how to release a version?

**Comment by benjaminhuo** [comment]
@wanjunlei Would you create a doc to elaborate how to initiate a release?

**Comment by wanjunlei** [comment]
> Hello,
> Just wanted to get the discussion started for cutting a new release to include changes since 0.5: #49, #50, and #51. I am not sure what the process is exactly... There was PR #47 for 0.5, but that went to `release-0.5` branch... So I imagine this should go into `release-0.6` branch that someone should create? Anyway just looking for guidance and to get the process going for a release if it's agreeable with everyone to publish a new release. Thanks.

@bojand I had created a branch release-0.6, the version 0.6.0 will be released based on this version. Do you still have to make changes to version 0.6.0? If not, I will release 0.6.0 later.

**Comment by wanjunlei** [comment]
@bojand I had to write a [release doc](https://github.com/kubesphere/fluentbit-operator/blob/master/RELEASE.md) to elaborate on how to release a version. Do you want to release the v0.6.0?

**Comment by benjaminhuo** [comment]
> @bojand I had to write a [release doc](https://github.com/kubesphere/fluentbit-operator/blob/master/RELEASE.md) to elaborate on how to release a version. Do you want to release the v0.6.0?

As @wanjunlei  mentioned,  @bojand you can follow the https://github.com/kubesphere/fluentbit-operator/blob/master/RELEASE.md to make necessary changes and then submit your PR to release-0.6 branch, and we'll push the docker image and create v0.6 release for you.

**Review by wanjunlei — APPROVED** [review]

**Pull request merged**
