### PR TITLE
Support for imagePullSecrets For fluentBit daemonset

### PR DESCRIPTION
**Pull request by deveshk0**
This PR add supports for imagePullSecrets for FluentBit Daemonset.

issue - https://github.com/kubesphere/fluentbit-operator/issues/92

### CODE REVIEW

**Comment by benjaminhuo** [comment]
Some changes are overlapping with https://github.com/kubesphere/fluentbit-operator/pull/93

**Comment by deveshk0** [comment]
I guess #93 is limited to operator and this introdues changes for daemonset

**Comment by wenchajun** [comment]
Thanks a lot. This may need to be revised as well(fluentbit-operator/api/fluentbitoperator/v1alpha2/zz_generated.deepcopy.go )
like this
--
if in.ImagePullSecrets != nil {
in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
*out = make([]v1.LocalObjectReference, len(*in))
copy(*out, *in)
}

**Comment by deveshk0** [comment]
ohh I thought It was auto-generated. I will update

**Comment by deveshk0** [comment]
@wenchajun I have updated it, Can you please have a look?

**Comment by wanjunlei** [comment]
You need to run `make manifest` and update the files.

**Comment by deveshk0** [comment]
@wanjunlei  Updated files.

**Review by wanjunlei — APPROVED** [review]

**Review by benjaminhuo — APPROVED** [review]

**Pull request merged**
